=== QasimRiaz/akomantoso/archived/release-2006-05-02/schemas/akomantoso10.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % PredefinedSimpleTypes SYSTEM "./pst.dtd">
%PredefinedSimpleTypes;

<!--  =====================================================================
Akoma Ntoso main schema


Release  25/04/2006
Fabio Vitali - University of Bologna

The present schema uses systematically XML design patterns as
described in http://www.xmlpatterns.com/
A few of them are explicitly mentioned, when their use or approach
was not felt clear or natural enough. Others are just used without
mentions.
=====================================================================  -->
<!--  =====================================================================

Main element groups

=====================================================================  -->
<!ENTITY % ANhier "section | part | paragraph | chapter | article" >
<!ENTITY % ANcontainers "div" >
<!ENTITY % ANblock "toc" >
<!ENTITY % ANinline "ref | def" >
<!ENTITY % ANtitleInline "ActType | ActTitle | ActNumber | ActProponent | ActDate | ActPurpose" >
<!ENTITY % ANmarker "noteref | recordedTime" >
<!ENTITY % HTMLcontainers "div" >
<!ENTITY % HTMLblock "p | ul | ol | table" >
<!ENTITY % HTMLinline "span | b | i | a" >
<!ENTITY % HTMLmarker "img" >
<!ENTITY % hierElements "%ANhier; | hcontainer" >
<!ENTITY % containerElements "%HTMLcontainers; | container" >
<!ENTITY % blockElements "%ANblock; | %HTMLblock; | block" >
<!ENTITY % inlineElements "%ANinline; | %HTMLinline; | inline | %ANtitleInline;" >
<!ENTITY % markerElements "%ANmarker; | %HTMLmarker; | marker" >
<!--  =====================================================================

Attribute groups

=====================================================================  -->
<!ENTITY % name " name  CDATA #REQUIRED" >
<!ENTITY % source " source  CDATA #REQUIRED" >
<!ENTITY % date " date  CDATA #REQUIRED" >
<!ENTITY % time " time  CDATA #REQUIRED" >
<!ENTITY % link " href  CDATA #REQUIRED" >
<!ENTITY % numb " numbering (on|off) 'off' " >
<!ENTITY % statusType "(omissis|repealed|suspended)" >
<!ENTITY % enactment " start  CDATA #IMPLIED end  CDATA #IMPLIED status %statusType; #IMPLIED" >
<!ENTITY % cellattrs " rowspan  CDATA '1'  colspan  CDATA '1' " >
<!ENTITY % HTMLattrs " class  CDATA #IMPLIED style  CDATA #IMPLIED title  CDATA #IMPLIED" >
<!ENTITY % idref " idref  CDATA #REQUIRED" >
<!ENTITY % idreq " id  CDATA #REQUIRED" >
<!ENTITY % idopt " id  CDATA #IMPLIED" >
<!ENTITY % corereq " %HTMLattrs;  %enactment;  %idreq; " >
<!ENTITY % coreopt " %HTMLattrs;  %enactment;  %idopt; " >
<!--  =====================================================================

Simple types (data values)

=====================================================================  -->
<!ENTITY % VersionType "(OriginalVersion|SingleVersion|MultipleVersions)" >
<!ENTITY % EventType "(Generation|Amendment|Repeal)" >
<!ENTITY % RefType "(Original|Passive|Active|Jurisprudence|HasAttachment|IsAttachment)" >
<!--  =====================================================================

Complex types (markup structures)

=====================================================================  -->
<!ENTITY % hierarchy "(num?,title?,(%hierElements;)+)" >
<!ENTITY % althierarchy "(num?,title?,(subdivision | speech | question)*)" >
<!ENTITY % blocksreq "(%blockElements;)+" >
<!ENTITY % blocksopt "(%blockElements;)+" >
<!ENTITY % inline "(#PCDATA |%inlineElements; | %markerElements;)*" >
<!ENTITY % markerreq "EMPTY" >
<!ENTITY % markeropt "EMPTY" >
<!ENTITY % referenceType "EMPTY" >
<!--  =====================================================================

Root element
Comment: One generic root element contains all document elements
Pattern: Universal Root
Reference: http://www.xmlpatterns.com/UniversalRootMain.shtml

=====================================================================  -->
<!ENTITY % DocumentTypes "(act | bill | doc | report | minutes)" >
<!ELEMENT akomantoso %DocumentTypes; >
<!ATTLIST akomantoso xmlns CDATA #FIXED "http://www.akomantoso.org/1.0">
<!--  =====================================================================

Document elements
Comment: All document elements share just two content models
Pattern: Consistent Element Set
Reference: http://www.xmlpatterns.com/ConsistentElementSetMain.shtml

=====================================================================  -->
<!ENTITY % HierarchicalStructure "(meta,preface?,preamble?,clauses,conclusions?,attachments?)" >
<!ENTITY % OpenStructure "(meta,preface?,preamble?,maincontent,conclusions?,attachments?)" >
<!ENTITY % DebateStructure "(meta,preface?,debate,conclusions?,attachments?)" >
<!ELEMENT act %HierarchicalStructure; >
<!ELEMENT bill %HierarchicalStructure; >
<!ELEMENT doc %OpenStructure; >
<!ELEMENT report %OpenStructure; >
<!ELEMENT minutes %DebateStructure; >
<!--  =====================================================================

AN common containers elements

=====================================================================  -->
<!ELEMENT preface %blocksopt; >
<!ELEMENT preamble %blocksopt; >
<!ELEMENT conclusions %blocksopt; >
<!ELEMENT attachments (attachment+)>
<!ELEMENT attachment %referenceType; >
<!ELEMENT clauses (%hierElements;)+>
<!ELEMENT debate (subdivision+)>
<!ELEMENT maincontent (%hierElements; | subdivision | item | %blockElements;)+>
<!ATTLIST maincontent %numb;  >
<!--  =====================================================================

Elements for hierarchical documents

=====================================================================  -->
<!ELEMENT section %hierarchy; >
<!ELEMENT part %hierarchy; >
<!ELEMENT paragraph %hierarchy; >
<!ELEMENT chapter %hierarchy; >
<!ENTITY % ArticleType "(num?,title?,clause+)" >
<!ELEMENT article %ArticleType; >
<!ENTITY % ClauseType "(num?,title?,(%blockElements;)+)" >
<!ELEMENT clause %ClauseType; >
<!ELEMENT num %inline; >
<!ELEMENT title %inline; >
<!ELEMENT subtitle %inline; >
<!--  =====================================================================

Elements for debates documents

=====================================================================  -->
<!ELEMENT subdivision %althierarchy; >
<!ELEMENT speech %blocksreq; >
<!ATTLIST speech by  CDATA #REQUIRED >
<!ELEMENT question %blocksreq; >
<!ATTLIST question by  CDATA #REQUIRED >
<!ENTITY % itemType "(num?,title?,subtitle?,(item | %blockElements;)+)" >
<!ELEMENT item %itemType; >
<!ATTLIST item %numb;  >
<!--  =====================================================================

AN block elements
Comment: the only AN-specific block is the table of content (TOC),
a structure containing toc items related to the various subparts of the
main document.

=====================================================================  -->
<!ELEMENT toc (tocitem+)>
<!ELEMENT tocitem %inline; >
<!ATTLIST tocitem %idref;  level  CDATA #REQUIRED >
<!--  =====================================================================

AN inline elements
Comment: AN-specific inline elements are connected to the
identification of elements that are corresponding to an inline
legal structure, regardless of their position in the document.

=====================================================================  -->
<!ELEMENT ActType %inline; >
<!ELEMENT ActTitle %inline; >
<!ELEMENT ActNumber %inline; >
<!ELEMENT ActProponent %inline; >
<!ELEMENT ActDate %inline; >
<!ELEMENT ActPurpose %inline; >
<!ELEMENT ref %inline; >
<!ATTLIST ref %link;  >
<!ELEMENT def %inline; >
<!ELEMENT noteref %markeropt; >
<!ATTLIST noteref num  CDATA #REQUIRED %link;  >
<!ELEMENT recordedTime %markeropt; >
<!ATTLIST recordedTime %time;  >
<!ENTITY % mod_entity "#PCDATA |quotedText | quotedStructure | %inlineElements; | %markerElements;" >

<!ELEMENT mod (%mod_entity;)*>
<!ATTLIST mod %coreopt;  >
<!ELEMENT quotedText %inline; >
<!ELEMENT quotedStructure (%hierElements; | %blockElements; | %containerElements;)+>
<!ATTLIST quotedStructure %corereq;  >
<!--  =====================================================================

Generic elements
Comment: All elements in this schema fall under one of five
content models: hierarchical container, container, block, inline
and mark. Besides named elements, the schema also provides for a
generic element for each of them, that can be used for markup that
fits the content models but can be specified by a precise name that
is not used in this schema. The 'name' attribute must be used for
naming the element.
It is also a characteristic of this schema that all named elements
are equivalent, and can be substituted to, the corresponding generic
element with their name as the value of the name attribute. Thus, by
definition, <p> = <block name="p">, <part> = <hcontainer name="part">,
<act> = <container name="act">, etc.
Pattern: Generic Document + Role Attribute
Reference: http://www.xmlpatterns.com/GenericDocumentMain.shtml +
http://www.xmlpatterns.com/RoleAttributeMain.shtml

=====================================================================  -->
<!ELEMENT hcontainer %hierarchy; >
<!ELEMENT container %blocksreq; >
<!ELEMENT block %inline; >
<!ELEMENT inline %inline; >
<!ELEMENT marker %markerreq; >
<!ATTLIST hcontainer %name;  >
<!ATTLIST container %name;  >
<!ATTLIST block %name;  >
<!ATTLIST inline %name;  >
<!ATTLIST marker %name;  >
<!--  =====================================================================

HTML elements
Comment: Many elements are drawn directly from HTML 4.0
Pattern: Reuse Document Types (partial)
Reference: http://www.xmlpatterns.com/ReuseDocumentTypesMain.shtml

=====================================================================  -->
<!ELEMENT div %blocksreq; >
<!ELEMENT p %inline; >
<!ENTITY % li_entity "#PCDATA |ul | ol | %inlineElements; | %markerElements;" >

<!ELEMENT li (%li_entity;)*>
<!ATTLIST li %coreopt;  >
<!ELEMENT span %inline; >
<!ELEMENT b %inline; >
<!ELEMENT i %inline; >
<!ELEMENT a %inline; >
<!ATTLIST a %link;  target  CDATA #IMPLIED >
<!ELEMENT img %markeropt; >
<!ATTLIST img src  CDATA #REQUIRED alt  CDATA #IMPLIED width  CDATA #IMPLIED height  CDATA #IMPLIED >
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT table (tr+)>
<!ATTLIST table %HTMLattrs;  width  CDATA #IMPLIED border  CDATA #IMPLIED cellspacing  CDATA #IMPLIED cellpadding  CDATA #IMPLIED >
<!ELEMENT tr (th | td)+>
<!ATTLIST tr %HTMLattrs;  >
<!ELEMENT th %inline; >
<!ELEMENT td %inline; >
<!ATTLIST th %cellattrs;  >
<!ATTLIST td %cellattrs;  >
<!--  =====================================================================

Metadata elements for acts, bills and generic documents

=====================================================================  -->
<!ENTITY % MetaSection "(descriptor,lifecycle?,persons?,notes*,proprietary*)" >
<!ELEMENT meta %MetaSection; >
<!ELEMENT descriptor (publication,otherpublications?,enactmentDate,editors,uri+,alias*,keywords?)>
<!ENTITY % publicationType "EMPTY" >
<!ELEMENT otherpublications (ripublication | errata)+>
<!ELEMENT publication %publicationType; >
<!ELEMENT ripublication %publicationType; >
<!ELEMENT errata %publicationType; >
<!ELEMENT enactmentDate %markeropt; >
<!ATTLIST enactmentDate %date;  >
<!ELEMENT editors (editor+)>
<!ELEMENT editor %markerreq; >
<!ATTLIST editor %date;  name  CDATA #REQUIRED uri  CDATA #IMPLIED contribution  CDATA #IMPLIED >
<!ELEMENT uri %markeropt; >
<!ATTLIST uri %link;  >
<!ELEMENT alias %markeropt; >
<!ATTLIST alias value  CDATA #REQUIRED >
<!ELEMENT keywords (keyword+)>
<!ATTLIST keywords dictionary  CDATA #REQUIRED >
<!ELEMENT keyword %markeropt; >
<!ATTLIST keyword value  CDATA #REQUIRED >
<!ELEMENT lifecycle (events?,references)>
<!ELEMENT events (event+)>
<!ELEMENT event %markerreq; >
<!ATTLIST event %date;  %source;  type %EventType; #IMPLIED >
<!ELEMENT references (reference+)>
<!ELEMENT reference %referenceType; >
<!ELEMENT persons (person+)>
<!ELEMENT person %markerreq; >
<!ATTLIST person short  CDATA #IMPLIED long  CDATA #REQUIRED >
<!ELEMENT notes (note)+>
<!ELEMENT note %blocksreq; >
<!ELEMENT proprietary ANY>
<!ATTLIST proprietary %source;  >
<!--  =====================================================================

End of Schema

=====================================================================  -->
<!ATTLIST section %corereq;  >
<!ATTLIST part %corereq;  >
<!ATTLIST paragraph %corereq;  >
<!ATTLIST chapter %corereq;  >
<!ATTLIST hcontainer %corereq;  >
<!ATTLIST subdivision %corereq;  >
<!ATTLIST speech %corereq;  >
<!ATTLIST question %corereq;  >
<!ATTLIST container %corereq;  >
<!ATTLIST div %corereq;  >
<!ATTLIST note %corereq;  >
<!ATTLIST preface %coreopt;  >
<!ATTLIST preamble %coreopt;  >
<!ATTLIST conclusions %coreopt;  >
<!ATTLIST num %coreopt;  >
<!ATTLIST title %coreopt;  >
<!ATTLIST subtitle %coreopt;  >
<!ATTLIST tocitem %coreopt;  >
<!ATTLIST ActType %coreopt;  >
<!ATTLIST ActTitle %coreopt;  >
<!ATTLIST ActNumber %coreopt;  >
<!ATTLIST ActProponent %coreopt;  >
<!ATTLIST ActDate %coreopt;  >
<!ATTLIST ActPurpose %coreopt;  >
<!ATTLIST ref %coreopt;  >
<!ATTLIST def %coreopt;  >
<!ATTLIST quotedText %coreopt;  >
<!ATTLIST block %coreopt;  >
<!ATTLIST inline %coreopt;  >
<!ATTLIST p %coreopt;  >
<!ATTLIST span %coreopt;  >
<!ATTLIST b %coreopt;  >
<!ATTLIST i %coreopt;  >
<!ATTLIST a %coreopt;  >
<!ATTLIST th %coreopt;  >
<!ATTLIST td %coreopt;  >
<!ATTLIST marker %corereq;  >
<!ATTLIST editor %corereq;  >
<!ATTLIST event %corereq;  >
<!ATTLIST person %corereq;  >
<!ATTLIST noteref %coreopt;  >
<!ATTLIST recordedTime %coreopt;  >
<!ATTLIST img %coreopt;  >
<!ATTLIST enactmentDate %coreopt;  >
<!ATTLIST uri %coreopt;  >
<!ATTLIST alias %coreopt;  >
<!ATTLIST keyword %coreopt;  >
<!ATTLIST attachment %corereq;  %link;  type %RefType; #REQUIRED >
<!ATTLIST reference %corereq;  %link;  type %RefType; #REQUIRED >
<!ATTLIST act contains %VersionType; 'OriginalVersion'  >
<!ATTLIST bill contains %VersionType; 'OriginalVersion'  >
<!ATTLIST doc contains %VersionType; 'OriginalVersion'  >
<!ATTLIST report contains %VersionType; 'OriginalVersion'  >
<!ATTLIST minutes contains %VersionType; 'OriginalVersion'  >
<!ATTLIST article %corereq;  >
<!ATTLIST clause %corereq;  >
<!ATTLIST item %corereq;  >
<!ATTLIST publication %coreopt;  %date;  type  CDATA #REQUIRED num  CDATA #IMPLIED >
<!ATTLIST ripublication %coreopt;  %date;  type  CDATA #REQUIRED num  CDATA #IMPLIED >
<!ATTLIST errata %coreopt;  %date;  type  CDATA #REQUIRED num  CDATA #IMPLIED >

=== QasimRiaz/akomantoso/releases/tags/release-2006-10-24b/examples/examples_with_DTD/sa_doc_20050829_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE akomantoso SYSTEM "../schemas/akomantoso10.dtd">
<?xml-stylesheet type="text/xsl" href="../styles/akomantoso.xsl"?>
<akomantoso xmlns="http://www.akomantoso.org/1.0">
    <doc>
        <meta>
            <descriptor>
                <publication date="2005-08-29" type="internal"/>
                <enactmentDate date="2005-08-29"/>
                <editors>
                    <editor date="2005-08-29" name="Mary Smith" id="clerk125" contribution="markup"
                    />
                </editors>
                <uri href="urn:an:sa_doc_20050829_en"/>
            </descriptor>
        </meta>
        <preface>
            <p class="important">PARLIAMENT OF THE REPUBLIC OF SOUTH AFRICA</p>
            <p class="important">ANNOUNCEMENTS, TABLINGS AND COMMITTEE REPORTS</p>
            <p class="important">MONDAY, 29 AUGUST 2005</p>
        </preface>
        <maincontent>
            <item id="toc">
                <title>TABLE OF CONTENTS</title>
                <toc>
                    <tocitem level="1" idref="announcements">ANNOUNCEMENTS</tocitem>
                    <tocitem level="2" idref="ann-NANCP">National Assembly and National Council of
                        Provinces</tocitem>
                    <tocitem level="3" idref="ann-NANCP-Bills">Introduction of Bills</tocitem>
                    <tocitem level="3" idref="ann-NANCP-Classification">Classification of Bills by
                        JTM</tocitem>
                    <tocitem level="2" idref="ann-NA">National Assembly</tocitem>
                    <tocitem level="3" idref="ann-NA-Membership">Membership of Committees</tocitem>
                    <tocitem level="1" idref="tablings">TABLINGS</tocitem>
                    <tocitem level="2" idref="tablings-NANCP">National Assembly and National Council
                        of Provinces</tocitem>
                    <tocitem level="3" idref="tablings-NANCP-Speaker">Speaker and Chairperson</tocitem>
                    <tocitem level="3" idref="tablings-NANCP-Minister">Minister in The Presidency</tocitem>
                    <tocitem level="1" idref="reports">COMMITTEE REPORTS</tocitem>
                    <tocitem level="2" idref="reports-NA">National Assembly</tocitem>
                    <tocitem level="3" idref="reports-NA-itm1">Finance</tocitem>
                </toc>
            </item>
            <item id="announcements">
                <title>ANNOUNCEMENTS</title>
                <item id="ann-NANCP">
                    <title>National Assembly and National Council of Provinces</title>
                    <subtitle>The Speaker and the Chairperson</subtitle>
                    <item id="ann-NANCP-Bills">
                        <num>1.</num>
                        <title>Introduction of Bills</title>
                        <item id="ann-NANCP-Bills-MinisterEnergy">
                            <num>(1)</num>
                            <title>The Minister of Minerals and Energy</title>
                            <item id="ann-NANCP-Bills-MinisterEnergy-B27">
                                <num>(i)</num>
                                <title>Diamonds Amendment Bill [B 27—2005] (National Assembly—sec
                                    75)</title>
                                <p>[Bill and prior notice of its introduction published in
                                    Government Gazette No 27929 of 19 August 2005.]</p>
                            </item>
                            <p>Introduction and referral to the <b>Portfolio Committee on Minerals
                                    and Energy</b> of the National Assembly, as well as referral to
                                the Joint Tagging Mechanism (JTM) for classification in terms of
                                Joint Rule 160, on 30 August 2005.</p>
                            <p>In terms of Joint Rule 154 written views on the classification of the
                                Bill may be submitted to the JTM within three parliamentary working
                                days.</p>
                        </item>
                    </item>
                    <item id="ann-NANCP-Classification">
                        <num>2.</num>
                        <title>Classification of Bill by Joint Tagging Mechanism:</title>
                        <item id="ann-NANCP-Classification-itm1">
                            <p>The Joint Tagging Mechanism (JTM) on 29 August 2005 in terms of Joint
                                Rule 160(4), classified the <ref href="urn:papi:sa_bill_2005_24"
                                    >Forestry Laws Amendment Bill [B 24—2005]</ref>, introduced in
                                the National Assembly, as a section 76 Bill and as a Bill falling
                                within the ambit of <ref href="urn:papi:sa_act_2003_41">section
                                    18(1) of the Traditional Leadership and Governance Framework
                                    Act, 2003 (Act No. 41 of 2003)</ref>.</p>
                        </item>
                    </item>
                </item>
                <item id="ann-NA">
                    <title>National Assembly</title>
                    <subtitle>The Speaker</subtitle>
                    <item id="ann-NA-Membership">
                        <num>1.</num>
                        <title>Membership of Committees</title>
                        <item id="ann-NA-Membership-itm1">
                            <p>The following changes have been made to the membership of
                                    <b>Portfolio Committees</b>, viz: </p>
                            <p>
                                <b>Housing: </b>
                            </p>
                            <p>Appointed: Cupido, Mr H B</p>
                            <p>Discharged: Khumalo, Rev M S </p>
                            <p>
                                <b>Trade and Industry: </b>
                            </p>
                            <p>Appointed: Cupido, Mr H B</p>
                        </item>
                    </item>
                </item>
            </item>
            <item id="tablings">
                <title>TABLINGS</title>
                <item id="tablings-NANCP">
                    <title>National Assembly and National Council of Provinces</title>
                    <item id="tablings-NANCP-Speaker">
                        <num>1.</num>
                        <title>The Speaker and the Chairperson</title>
                        <item id="tablings-NANCP-Speaker-itm1">
                            <p>Report and Financial Statements of the Municipal Demarcation Board
                                for 2004-2005, including the Report of the Auditor-General on the
                                Financial Statements for 2004-2005 [RP 149-2005].</p>
                        </item>
                    </item>
                    <item id="tablings-NANCP-Minister">
                        <num>2.</num>
                        <title>The Minister in The Presidency</title>
                        <item id="tablings-NANCP-Minister-itm1">
                            <p>Report and Financial Statements of the International Marketing
                                Council (IMC) for 2004-2005, including the Report of the Auditor-
                                General on the Financial Statements for 2004-2005.</p>
                        </item>
                    </item>
                </item>
            </item>
            <item id="reports">
                <title>COMMITTEE REPORTS</title>
                <item id="reports-NA">
                    <title>National Assembly:</title>
                    <item id="reports-NA-itm1">
                        <p>Report of the Portfolio Committee on Finance on the <b>Agreement between
                                the Government of the Republic of South Africa and the Government of
                                Malaysia for the Avoidance of Double Taxation and the Prevention of
                                Fiscal Evasion with respect to Taxes</b>, dated 17 August 2005:</p>
                        <p class="indented">The Portfolio Committee on Finance, having considered
                            the request for approval by Parliament of the <b>Agreement between the
                                Government of the Republic of South Africa and the Government of
                                Malaysia for the Avoidance of Double Taxation and the Prevention of
                                Fiscal Evasion with respect to Taxes</b>, referred to it, recommends
                            that the House, in terms of <ref href="urn:papi:sa_const_en#art231-cla2"
                                >section 231(2) of the Constitution</ref>, approve the said
                            Agreement.</p>
                        <p>Request to be considered.</p>
                    </item>
                </item>
            </item>
        </maincontent>
    </doc>
</akomantoso>
